Fixed and updated Turkish translations
organicmaps/organicmaps.github.io pull request #143
Opened 2023-04-07 16:39 UTC by MetehanOzyurek

* Translated news:
> 2023-02-28
> 2023-03-09
> 2023-04-06
* Fixed & updated Turkish translations for donate

2023-04-08 13:09 UTC, biodranik reviewed
@rtsisyk do we support Turkish via Weblate?

2023-04-08 20:05 UTC, MetehanOzyurek commented
> @rtsisyk do we support Turkish via Weblate?

No, I prefer to translate on GitHub. 
![Screenshot_20230408-230252.png](https://user-images.githubusercontent.com/80093621/230740523-0c612a98-31b9-42bc-aaaa-0d7a8e971d67.png)

2023-04-08 20:06 UTC, MetehanOzyurek commented
@biodranik 
https://hosted.weblate.org/projects/organicmaps/website/

2023-04-08 21:10 UTC, biodranik requested changes

2023-04-08 21:10 UTC, biodranik commented on content/news/2023-04-06/150/index.tr.md
> +*  Yer imlerini açarken artık alt sayfa kapatılmıyor
```suggestion
* F-Droid sürümünde yönlendirme yapmak artık harita indirmeyi durdurmuyor
* OsmLoginFragment'taki çökme sorunu düzeltildi
* Uyarı kutusu için koyu tema desteği eklendi
* Yer imlerini açarken artık alt sayfa kapatılmıyor
```

2023-04-08 21:10 UTC, biodranik commented on content/news/2023-02-28/143/index.tr.md
> +title: "OpenStreetMap ve Organic Maps, Dr. Bilgehan Çevik (https://www.openstreetmap.org/user/pedrito1414/diary/401061)'e Türkiye'de yardımcı oldu. "
Please don't use markdown/links in titles.
```suggestion
title: "OpenStreetMap ve Organic Maps, Dr. Bilgehan Çevik'e Türkiye'de yardımcı oldu"
```

2023-04-08 21:10 UTC, biodranik commented on content/news/2023-04-06/150/index.tr.md
> +slug: "you-can-easily-find-the-nearest-cannabis-store-with-the-latest-organic-maps-update"
If you want, you may try to use some turkish letters for the slug.

2023-04-09 09:51 UTC, biodranik approved these changes
Thank you!

2023-04-09 09:51 UTC, merged