Rework donation page
organicmaps/organicmaps.github.io pull request #48
Opened 2022-09-08 08:51 UTC by rtsisyk

<img width="457" alt="image" src="https://user-images.githubusercontent.com/1799054/189079111-d53600cc-012a-4fac-beed-d18467dfc689.png">

2022-09-09 00:16 UTC, biodranik requested changes

2022-09-09 00:16 UTC, biodranik commented on templates/shortcodes/donate_buttons.html
> +      for (var i = 0; i < navigator.languages.length; i++)
Ты специально пишешь код без отступов? Глаза вытекают. Исправь, пожалуйста.

2022-09-09 00:16 UTC, biodranik commented on templates/shortcodes/donate_buttons.html
> +          return true;
Такое мы пишем в одну строку без скобок.

2022-09-09 00:16 UTC, biodranik commented on templates/shortcodes/donate_buttons.html
> +    document.getElementById('eps').style.display = 'none';
Почему выше null а тут none? Сделай консистентно, а то выглядит как бага.

2022-09-09 00:16 UTC, biodranik commented on templates/shortcodes/donate_buttons.html
> +  <a href="https://t.me/OrganicMapsRu/23361"><img id="mir" style="display: none;" src="/images/donates/mir.svg" alt="Telegram в рублях"></a>
Ещё есть евро донаты через телегу, можно показывать для !ru

2022-09-09 04:25 UTC, rtsisyk commented on templates/shortcodes/donate_buttons.html
> +  <a href="https://t.me/OrganicMapsRu/23361"><img id="mir" style="display: none;" src="/images/donates/mir.svg" alt="Telegram в рублях"></a>
Не нужен нам этот метод.

2022-09-09 04:26 UTC, rtsisyk commented on templates/shortcodes/donate_buttons.html
> +          return true;
Почему раньше было со скобками? У нас есть codestyle по javascript? Форматтер есть? Пока этого нет, я буду писать как мне удобнее.

2022-09-09 04:26 UTC, rtsisyk commented on templates/shortcodes/donate_buttons.html
> +      for (var i = 0; i < navigator.languages.length; i++)
Просто случайность

2022-09-09 04:52 UTC, rtsisyk commented on templates/shortcodes/donate_buttons.html
> +    document.getElementById('eps').style.display = 'none';
Потому что оно включает первый и отключает второй для того, чтобы число методов было фиксированным. EPS здесь выбран как потенциально наименее нужный. На странице оплаты всё равно можно будет его выбрать потом. Stripe сам показывает наиболее подходящие методы оплаты в зависимости от региона. Повторять эту логику здесь полностью я не буду.

2022-09-09 04:57 UTC, rtsisyk commented on content/donate/index.md
>  - No crapware
Специально перечислено по максимуму для создания лучшего эффекта. Я бы хотел оставить как есть.

2022-09-09 04:59 UTC, rtsisyk commented on templates/shortcodes/donate_buttons.html
> +      for (var i = 0; i < navigator.languages.length; i++)
Поправил здесь.

2022-09-09 12:55 UTC, merged

2022-09-10 13:03 UTC, biodranik commented on templates/shortcodes/donate_buttons.html
> +          return true;
Потому что мы используем те же правила, что и в C++. Хуже всего, когда каждый новый программист будет писать по-своему.