Detect and serve localized donation page
organicmaps/organicmaps.github.io pull request #60
Opened 2022-11-20 18:17 UTC by biodranik

Надо продумать cookie, чтобы можно было таки переключиться на английскую после редиректа.
Или сделать как-то ещё умнее/хитрее, сразу для любой страницы сайта.
@rtsisyk есть идеи?

2022-11-28 07:09 UTC, rtsisyk requested changes

2022-11-28 07:09 UTC, rtsisyk commented on functions/donate.ts
> +// Redirects users from the default en donate page to the appropriate localized version.
Как это работает и в какой момент выполняется? Можно ли обойтись редиректом на фронтенде и не добавлять вендор-лок от клаудфлера и здесь тоже?

2022-11-28 08:29 UTC, biodranik commented on functions/donate.ts
> +// Redirects users from the default en donate page to the appropriate localized version.
Выполняется для всех роутов /donate и /donate/ (по имени файла и папок), подробнее написано здесь: https://developers.cloudflare.com/pages/platform/functions/routing/

С учётом следующего PR с редиректом на фронте, этот, получается, не нужен, т.к. следующий более универсальный.

Преимущества этого подхода в скорости, т.к. нет ненужной загрузки en страницы в браузере, запуска там js кода, и последующей загрузки локализованной страницы.

Есть, правда, нюанс, что по /donate появляется версия на другом языке. В HTTP же нет штатного способа отдать страницу по-другому адресу с одновременным обновлением адреса, кроме редиректов, верно?

2022-11-28 19:06 UTC, rtsisyk commented on functions/donate.ts
> +// Redirects users from the default en donate page to the appropriate localized version.
> Есть, правда, нюанс, что по /donate появляется версия на другом языке. В HTTP же нет штатного способа отдать страницу по-другому адресу с одновременным обновлением адреса, кроме редиректов, верно?

Отдавать можно какой угодно контент, но чтобы поменять URL в браузере нужен или серверный Location: redirect или махинации с адресной строкой в JS.

Мне в целом не очень нравится идея залезания на лок клаудфлера. Пусть будет пока редирект на фронтенде. Это можно залить в любой хостинг.

2022-12-11 10:45 UTC, biodranik commented
Localization redirect is now done in browsers. This PR can be used later as an example of enabling [Cloudflare Functions](https://developers.cloudflare.com/pages/platform/functions/) for Pages.

2022-12-11 10:45 UTC, closed without merging