New site
organicmaps/organicmaps.github.io pull request #7
Opened 2021-06-28 08:25 UTC by biodranik

@vitaly-zdanevich я походу что-то сломал? Куда-то пропал твой PR. Хотел сделать ветку в нашем репо из твоего PR, чтобы мы все удобно сначала туда все фиксы кидали, а как вылижем, потом влили в мастер.

@rtsisyk я поправил вёрстку, посмотри пожалуйста, только надо собрать свежую zola с ветки next через cargo build --release

2021-06-28 15:53 UTC, vitaly-zdanevich commented
Закрыл PR
![image](https://user-images.githubusercontent.com/3514015/123666686-1c597d00-d842-11eb-84e3-6869649aa0c1.png)

2021-06-28 15:54 UTC, vitaly-zdanevich commented
> только надо собрать свежую zola с ветки next через cargo build --release

В чем отличие от текущей релизной версии 0.13.0?

2021-06-28 16:00 UTC, vitaly-zdanevich commented on content/_index.md
> +[appstore]: https://apps.apple.com/app/organic-maps/id1567437057 "Install from the AppStore"
Duplicate line?

2021-06-28 16:56 UTC, biodranik commented on content/_index.md
> +[appstore]: https://apps.apple.com/app/organic-maps/id1567437057 "Install from the AppStore"
Thanks, fixed!

2021-06-29 13:21 UTC, rtsisyk commented on sass/main.scss
> +main {
Ребят, ну скопируйте CSS с текущего сайта. Рендер гитхаба выглядит сильно лучше, чем то, что делаем мы сейчас. Давайте не будем изобреть колесо и просто скопируем стиль и верстку у гитхаба. Можно прям сайт открыть и оттуда скопировать. Либо поискать как называется данная тема Jinja и скопировать оттуда.

2021-06-29 13:21 UTC, rtsisyk requested changes
Верстка по прежнему хуже GitHub.

2021-06-29 16:35 UTC, vitaly-zdanevich commented on sass/main.scss
> +main {
Jekyll:
![image](https://user-images.githubusercontent.com/3514015/123835338-11215280-d911-11eb-8d32-fb0c9978f0f9.png)

Zola:
![image](https://user-images.githubusercontent.com/3514015/123835356-18e0f700-d911-11eb-993c-f1bb296a8ffe.png)

Дело в цветах линков и расстоянии между строками?

2021-06-29 19:50 UTC, biodranik commented
@vitaly-zdanevich @rtsisyk у меня в сток версии zola вроде как svg картинки отдавались без content-type, при `zola serve`. После сборки свежачка всё норм. `zola build` при этом работает норм везде.

2021-06-29 19:58 UTC, vitaly-zdanevich commented
Так отдавать файлы будет Гитхаб, точнее даже CloudFront.

2021-07-01 14:52 UTC, rtsisyk approved these changes
Ребят, теперь реально выглядит не хуже предыдущего. Отличная работа! Approved.

2021-07-01 14:54 UTC, rtsisyk commented on sass/main.scss
> +main {
Расстояние и шрифты. Если сможете  - покрутите. Но в целом уже норм.

2021-07-01 14:57 UTC, rtsisyk commented
Сквошните перед пушем.

2021-07-01 16:03 UTC, merged